# Generated by Django 4.2.7 on 2023-11-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LibroEditorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.editorial",
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="libreria.libro"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
